[AudioManager]
soundpath = "../audio/sounds/"
musicpath = "../audio/music/"
music_volume_ratio = 0.33
music_runner = "bfmv-hand-of-blood.ogg"
music_shooter = "hiroshi-okubo-arcade-ripping-air.ogg"

[InputManager]
try_detect_joystick = true
joystick_number = 0

[SerialDevice]
reading_retry_time_ms = 10

[Bicycle]
rpm_to_logical_speed = 15.0

[RealBicycle]
max_string_response = 16

[RealPolar]
max_string_response = 140
